### ISSUE TITLE
Delete wasabi-tmp branch

### ISSUE THREAD

**Issue by nopara73** [VitalElement/AvalonStudio.Shell#12]
I've noticed there's a `wasabi-tmp` branch that's not used anymore in this repo. This is a bit confusing it can be deleted.  

For help I paste here the commands: https://stackoverflow.com/a/10999165/2061103

```sh
git branch -D wasabi-tmp
git push origin --delete wasabi-tmp
```

**Comment by danwalmsley** [comment]
Done
