### ISSUE TITLE
Software hangs when `.AfterSetup` throws exception

### ISSUE THREAD

**Issue by nopara73** [VitalElement/AvalonStudio.Shell#26]
Put `throw new Exception();` to `.AfterSetup(_ =>` and the software will hang instead of crash. This is a deeper look into https://github.com/zkSNACKs/WalletWasabi/issues/2843.

**Comment by danwalmsley** [comment]
This is a Avalonia issue, will reopen there!

**Comment by danwalmsley** [comment]
Hang is inside wasabi
