### ISSUE TITLE
Sample app needs update after Dock update

### ISSUE THREAD

**Issue by amis92** [VitalElement/AvalonStudio.Shell#7]
Right now there's a problem with View location, as it tries to find view by string replacement in `AvaloniaStudioDocumentTab` type name from `DockExtensions`.

I'm interested in this project and may help with development, but since the sample app doesn't really work, it's hard to get a grip of functionality.

While at it, I think a NuGet.config with appropriate feeds added would be nice, since otherwise this project can't be built from fresh clone.

Aaand there's no License. :)

Awesome work!

**Comment by nopara73** [comment]
@amis92 Just talked about this today. This is not mature enough for NuGet yet.  

The maintainers will answer the sample app question, but FYI, you can check out this app, which is built, using this repo as a submodule: https://github.com/zkSNACKs/WalletWasabi/tree/master/WalletWasabi.Gui

**Comment by amis92** [comment]
Oh, I'm not saying this should be published on NuGet, rather that the solution included can't be built because, standalone, this repo doesn't contain NuGet.config that'd provide the *feeds* this solution *consumes* packages from. AFAIK, these should be added:

```xml
    <add key="AvaloniCI" value="https://www.myget.org/F/avalonia-ci/api/v2" />
    <add key="XamlBehaviors" value="https://www.myget.org/F/xamlbehaviors-nightly/api/v2" />
```

from https://github.com/VitalElement/AvalonStudio/blob/617cbb896a7a58bf347ee6b89fed2ddfd9dee4c4/nuget.config

**Comment by danwalmsley** [comment]
@amis92 updated and fixed!
